name: Deploy to VPS

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /usr/local/lsws/dkdevelopers.co.in/public_html
            git pull origin main
            pm2 stop dkdeveloper
            npm install
            npm run build
            pm2 start dkdeveloper